---
- hosts: 172.31.34.97
  become: yes
  tasks: 
  - name: install git
    apt:
      name: git
      state: present

  - name: tree
    apt:
      name: tree
      statee: present

  - name: wget
    apt: 
      name: wget
      state: present      
