---
- hosts: all
  tasks: 
  - name: I want to ping all nodes
    ping:
  - name: I want to install webserver on ubuntu ansible server
    apt:
     name: apache2
     state: present

  - name: I want to install tree on ubuntu anible nodes
    apt:
      name: tree
      state: present
  