---
- hosts: 172.31.34.97
  become: yes
  tasks:
  - include: myfile.yml

  - name: I want to install webser
    apt: 
      name: apache2
      state: present   
  - name: copy index file into node side
    copy: 
      src: myindexpage
      dest: /var/www/html/index.html  
    notify: restartwebserver    

  - name: copy dyno files into nodes
    template:
      src: mydynoindex.j2
      dest: /var/www/html/index.html 
    notify: restartwebserver

  - name: download file
    get_url: 
      url: https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.387.3/jenkins.war 
      dest: /home/ubuntu/jenkins.msi
      force_basic_auth: yes   


  handlers:     
  - name: restartwebserver
    service:
      name: apache2
      state: restarted     

