---
- hosts: 172.31.34.97
  become: yes
  tasks:
  - include: myfile.yml

  - name: I want to install webser
    apt: 
      name: apache2
      state: present   
  - name: copy index file into node side
    copy: 
      src: myindexpage
      dest: /var/www/html/index.html      

