---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install java on ubuntu
    apt: 
       name: "{{myjavaubuntu}}"
       state: present
    when: ansible_os_family =="Debian" 

  - name: install java on redhat
    yum:
       name: "{{myjavaredhat}}"
       state: present
    when: ansible_os_family =="RedHat"   