---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: I want install webser on ubuntu node
    apt: 
       name: apache2
       state: present
  - name: i want to start webserver on ubuntu nodes
    service: 
      name: apache2
      state: started
