---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: I want install webser on ubuntu node
    apt: 
       name: apache2
       state: present
    when: ansible_os_family =="Debian"   
  - name: i want to start webserver on ubuntu nodes
    service: 
       name: apache2
       state: started
    when: ansible_os_family =="Debian" 
  - name: I want to install webserver in "REdHat" nodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: I want to start webserver on "RedHat" nodes
    service:
       name: httpd
       state: started
    when: ansible_os_family =="RedHat"

#   "RedHat" =="Debian"
#   "Debian" =="Debian"     
